# Initial Data Exploration
SELECT * FROM customer_behavior1.customer_data;

SELECT COUNT(*) FROM customer_data;

SELECT * FROM customer_data
LIMIT 5;


# Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS revenue 
FROM customer_data
GROUP BY gender;


# Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer_data
WHERE discount_applied = 'Yes' 
  AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_data);


# Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating), 2) AS 'Average product rating'
FROM customer_data
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC 
LIMIT 5;


# Q4. Compare average purchase amount between standard and express shipping 
SELECT shipping_type, ROUND(AVG(purchase_amount), 2)
FROM customer_data
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


# Q5. Do subscribed customers spend more? Compare average spend and total revenue 
SELECT subscription_status, 
       COUNT(customer_id) AS total_customer,
       ROUND(AVG(purchase_amount), 2) AS avg_spend,
       ROUND(SUM(purchase_amount), 2) AS total_revenue 
FROM customer_data
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;


# Q6. Which 5 products have the highest percentage of purchases with discount applied?
SELECT item_purchased,
       ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customer_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


# Q7. Segment customers into New, Returning, and Loyal based on their total 
# number of previous purchases, and show the count of each segment 
WITH customer_type AS (
    SELECT customer_id, previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'new'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'returning'
            ELSE 'loyal'
        END AS customer_segment
    FROM customer_data
)
SELECT customer_segment, COUNT(*) AS `number of customer`
FROM customer_type
GROUP BY customer_segment;


# Q8. What are the 3 most purchased products within each category?
WITH item_count AS (
    SELECT category, 
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) as row_num
    FROM customer_data
    GROUP BY category, item_purchased
)
SELECT category, 
       item_purchased, 
       total_orders
FROM item_count
WHERE row_num <= 3;


# Q9. Are customers who are repeat buyers also most likely to subscribe?
SELECT 
    CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyer (> 5)'
        ELSE 'Regular Buyer (<= 5)' 
    END AS buyer_category,
    COUNT(customer_id) AS total_customers_in_group,
    ROUND(100 * AVG(subscription_status = 'Yes'), 2) AS subscription_rate_percentage
FROM customer_data
GROUP BY buyer_category;


# Q10. What is the revenue contribution of each age group?
SELECT age_group, ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer_data
GROUP BY age_group
ORDER BY total_revenue DESC;